import './globals.scss'
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import { Montserrat } from 'next/font/google'


const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'My List App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href='/listLogo.png' />
      </head>
      <body className={montserrat.className}>
        <div className='container mt-3'>
          <div className='mt-3'>
            <ToastContainer />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
